"""from markdown to html 

Revision ID: 9be2054446dd
Revises: None
Create Date: 2016-06-14 10:25:38.059000

"""

# revision identifiers, used by Alembic.
revision = '9be2054446dd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
